server:
  port: 8050
eureka:
  client:
    service-url:
       defaultZone : http://root:root@discovery2:8762/eureka/,http://root:root@discovery:8761/eureka/
spring:
  application:
    name: file-upload
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2500Mb
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
